version: '3.9'
services:
  # Apache webserver service
  web:
    container_name: noa91php74
    image: rascar/docker-noalyss:9100
    ## In case you need to build locally your image 
    #build:
    #  context: .
    #  dockerfile: Dockerfile  
    ports:
      - 8080:80  
    depends_on:
      - postgres

  postgres:
    image: postgres:12.7
    container_name: postgres127
    environment:
      POSTGRES_DB: noalyss_sql
      POSTGRES_USER: noalyss_sql
      POSTGRES_PASSWORD: dany
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  # Adminer 192.168.1.35:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgdamin
    environment:
      # Default email for pgAdmin 4
      PGADMIN_DEFAULT_EMAIL: thierry.nancy@gmail.com
      # Password for accessing pgAdmin 4
      PGADMIN_DEFAULT_PASSWORD: xylopho00
    ports:
      # Expose pgadmin on 5050 
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always
volumes:
  pgadmin_data:


